"""empty message

Revision ID: b49b771e56e4
Revises: 
Create Date: 2022-03-20 19:18:38.031450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49b771e56e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptitle', sa.String(length=80), nullable=True),
    sa.Column('desc', sa.String(length=512), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('brooms', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('ptype', sa.String(length=64), nullable=True),
    sa.Column('locat', sa.String(length=128), nullable=True),
    sa.Column('photo', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
